const tipeBarangs = ['Persediaan', 'Jasa'];
const badanUsahas = ['PT','CV','UD'];
const statusPiutangs = ['Lancar','Tidak Lancar'];
const statusPelanggans = ['Progress','Survey','Prepare','Installed','Uninstalled'];
const alamats = {
  'Aceh': [
    'Simeulue',
    'Aceh Singkil',
    'Aceh Selatan',
    'Aceh Tenggara',
    'Aceh Timur',
    'Aceh Tengah',
    'Aceh Barat',
    'Aceh Besar',
    'Pidie',
    'Bireuen',
    'Aceh Utara',
    'Aceh Barat Daya',
    'Gayo Lues',
    'Aceh Tamiang',
    'Nagan Raya',
    'Aceh Jaya',
    'Bener Meriah',
    'Pidie Jaya',
    'Banda Aceh',
    'Sabang',
    'Langsa',
    'Lhokseumawe',
    'Subulussalam',
  ],

  'Bali': [
    'Jembrana',
    'Tabanan',
    'Badung',
    'Gianyar',
    'Klungkung',
    'Bangli',
    'Karang Asem',
    'Buleleng',
    'Denpasar',
  ],

  'Banten': [
    'Pandeglang',
    'Lebak',
    'Tangerang',
    'Serang',
    'Tangerang',
    'Cilegon',
    'Serang',
    'Tangerang Selatan',
  ],

  'Bengkulu': [
    'Bengkulu Selatan',
    'Rejang Lebong',
    'Bengkulu Utara',
    'Kaur',
    'Seluma',
    'Mukomuko',
    'Lebong',
    'Kepahiang',
    'Bengkulu Tengah',
    'Bengkulu',
  ],

  'DKI Jakarta': [
    'Kepulauan Seribu',
    'Jakarta Selatan',
    'Jakarta Timur',
    'Jakarta Pusat',
    'Jakarta Barat',
    'Jakarta Utara',
  ],

  'Gorontalo': [
    'Boalemo',
    'Gorontalo',
    'Pohuwato',
    'Bone Bolango',
    'Gorontalo Utara',
    'Gorontalo',
  ],

  'Jambi': [
    'Kerinci',
    'Merangin',
    'Sarolangun',
    'Batang Hari',
    'Muaro Jambi',
    'Tanjung Jabung Timur',
    'Tanjung Jabung Barat',
    'Tebo',
    'Bungo',
    'Jambi',
    'Sungai Penuh',
  ],

  'Jawa Barat': [
    'Bogor',
    'Sukabumi',
    'Cianjur',
    'Bandung',
    'Garut',
    'Tasikmalaya',
    'Ciamis',
    'Kuningan',
    'Cirebon',
    'Majalengka',
    'Sumedang',
    'Indramayu',
    'Subang',
    'Purwakarta',
    'Karawang',
    'Bekasi',
    'Bandung Barat',
    'Pangandaran',
    'Bogor',
    'Sukabumi',
    'Bandung',
    'Cirebon',
    'Bekasi',
    'Depok',
    'Cimahi',
    'Tasikmalaya',
    'Banjar',
  ],

  'Jawa Tengah': [
    'Cilacap',
    'Banyumas',
    'Purbalingga',
    'Banjarnegara',
    'Kebumen',
    'Purworejo',
    'Wonosobo',
    'Magelang',
    'Boyolali',
    'Klaten',
    'Sukoharjo',
    'Wonogiri',
    'Karanganyar',
    'Sragen',
    'Grobogan',
    'Blora',
    'Rembang',
    'Pati',
    'Kudus',
    'Jepara',
    'Demak',
    'Semarang',
    'Temanggung',
    'Kendal',
    'Batang',
    'Pekalongan',
    'Pemalang',
    'Tegal',
    'Brebes',
    'Magelang',
    'Surakarta',
    'Salatiga',
    'Semarang',
    'Pekalongan',
    'Tegal',
  ],

  'Jawa Timur': [
    'Pacitan',
    'Ponorogo',
    'Trenggalek',
    'Tulungagung',
    'Blitar',
    'Kediri',
    'Malang',
    'Lumajang',
    'Jember',
    'Banyuwangi',
    'Bondowoso',
    'Situbondo',
    'Probolinggo',
    'Pasuruan',
    'Sidoarjo',
    'Mojokerto',
    'Jombang',
    'Nganjuk',
    'Madiun',
    'Magetan',
    'Ngawi',
    'Bojonegoro',
    'Tuban',
    'Lamongan',
    'Gresik',
    'Bangkalan',
    'Sampang',
    'Pamekasan',
    'Sumenep',
    'Kediri',
    'Blitar',
    'Malang',
    'Probolinggo',
    'Pasuruan',
    'Mojokerto',
    'Madiun',
    'Surabaya',
    'Batu',
  ],


  'Kalimantan Barat': [
    'Sambas',
    'Bengkayang',
    'Landak',
    'Mempawah',
    'Sanggau',
    'Ketapang',
    'Sintang',
    'Kapuas Hulu',
    'Sekadau',
    'Melawi',
    'Kayong Utara',
    'Kubu Raya',
    'Pontianak',
    'Singkawang',
  ],

  'Kalimantan Selatan': [
    'Tanah Laut',
    'Baru',
    'Banjar',
    'Barito Kuala',
    'Tapin',
    'Hulu Sungai Selatan',
    'Hulu Sungai Tengah',
    'Hulu Sungai Utara',
    'Tabalong',
    'Tanah Bumbu',
    'Balangan',
    'Banjarmasin',
    'Banjar Baru',
  ],

  'Kalimantan Tengah': [
    'aringin Barat',
    'aringin Timur',
    'Kapuas',
    'Barito Selatan',
    'Barito Utara',
    'Sukamara',
    'Lamandau',
    'Seruyan',
    'Katingan',
    'Pulang Pisau',
    'Gunung Mas',
    'Barito Timur',
    'Murung Raya',
    'Palangka Raya',
  ],
  'Kalimantan Timur': [
    'Paser',
    'Kutai Barat',
    'Kutai Kartanegara',
    'Kutai Timur',
    'Berau',
    'Penajam Paser Utara',
    'Mahakam Hulu',
    'Balikpapan',
    'Samarinda',
    'Bontang',
  ],

  'Kalimantan Utara': [
    'Malinau',
    'Bulungan',
    'Tana Tidung',
    'Nunukan',
    'Tarakan',
  ],

  'Kepulauan Bangka Belitung': [
    'Bangka',
    'Belitung',
    'Bangka Barat',
    'Bangka Tengah',
    'Bangka Selatan',
    'Belitung Timur',
    'Pangkal Pinang',
  ],

  'Kepulauan Riau': [
    'Karimun',
    'Bintan',
    'Natuna',
    'Lingga',
    'Kepulauan Anambas',
    'Batam',
    'Tanjung Pinang',
  ],

  'Lampung': [
    'Lampung Barat',
    'Tanggamus',
    'Lampung Selatan',
    'Lampung Timur',
    'Lampung Tengah',
    'Lampung Utara',
    'Way Kanan',
    'Tulangbawang',
    'Pesawaran',
    'Pringsewu',
    'Mesuji',
    'Tulang Bawang Barat',
    'Pesisir Barat',
    'Bandar Lampung',
    'Metro',
  ],

  'Maluku': [
    'Maluku Tenggara Barat',
    'Maluku Tenggara',
    'Maluku Tengah',
    'Buru',
    'Kepulauan Aru',
    'Seram Bagian Barat',
    'Seram Bagian Timur',
    'Maluku Barat Daya',
    'Buru Selatan',
    'Ambon',
    'Tual',
  ],

  'Maluku Utara': [
    'Halmahera Barat',
    'Halmahera Tengah',
    'Kepulauan Sula',
    'Halmahera Selatan',
    'Halmahera Utara',
    'Halmahera Timur',
    'Pulau Morotai',
    'Pulau Taliabu',
    'Ternate',
    'Tidore Kepulauan',
  ],

  'Nusa Tenggara Barat': [
    'Lombok Barat',
    'Lombok Tengah',
    'Lombok Timur',
    'Sumbawa',
    'Dompu',
    'Bima',
    'Sumbawa Barat',
    'Lombok Utara',
    'Mataram',
    'Bima',
  ],

  'Nusa Tenggara Timur': [
    'Sumba Barat',
    'Sumba Timur',
    'Kupang',
    'Timor Tengah Selatan',
    'Timor Tengah Utara',
    'Belu',
    'Alor',
    'Lembata',
    'Flores Timur',
    'Sikka',
    'Ende',
    'Ngada',
    'Manggarai',
    'Rote Ndao',
    'Manggarai Barat',
    'Sumba Tengah',
    'Sumba Barat Daya',
    'Nagekeo',
    'Manggarai Timur',
    'Sabu Raijua',
    'Malaka',
    'Kupang',
  ],

  'Papua': [
    'Merauke',
    'Jayawijaya',
    'Jayapura',
    'Nabire',
    'Kepulauan Yapen',
    'Biak Numfor',
    'Paniai',
    'Puncak Jaya',
    'Mimika',
    'Boven Digoel',
    'Mappi',
    'Asmat',
    'Yahukimo',
    'Pegunungan Bintang',
    'Tolikara',
    'Sarmi',
    'Keerom',
    'Waropen',
    'Supiori',
    'Mamberamo Raya',
    'Nduga',
    'Lanny Jaya',
    'Mamberamo Tengah',
    'Yalimo',
    'Puncak',
    'Dogiyai',
    'Intan Jaya',
    'Deiyai',
    'Jayapura',
  ],

  'Papua Barat': [
    'Fakfak',
    'Kaimana',
    'Teluk Wondama',
    'Teluk Bintuni',
    'Manokwari',
    'Sorong Selatan',
    'Sorong',
    'Raja Ampat',
    'Tambrauw',
    'Maybrat',
    'Manokwari Selatan',
    'Pegunungan Arfak',
    'Sorong',
  ],

  'Riau': [
    'Kuantan Singingi',
    'Indragiri Hulu',
    'Indragiri Hilir',
    'Pelalawan',
    'Siak',
    'Kampar',
    'Rokan Hulu',
    'Bengkalis',
    'Rokan Hilir',
    'Kepulauan Meranti',
    'Pekanbaru',
    'Dumai',
  ],

  'Sulawesi Barat': [
    'Majene',
    'Polewali Mandar',
    'Mamasa',
    'Mamuju',
    'Mamuju Utara',
    'Mamuju Tengah',
  ],

  'Sulawesi Selatan': [
    'Kepulauan Selayar',
    'Bulukumba',
    'Bantaeng',
    'Jeneponto',
    'Takalar',
    'Gowa',
    'Sinjai',
    'Maros',
    'Pangkajene Dan Kepulauan',
    'Barru',
    'Bone',
    'Soppeng',
    'Wajo',
    'Sidenreng Rappang',
    'Pinrang',
    'Enrekang',
    'Luwu',
    'Tana Toraja',
    'Luwu Utara',
    'Luwu Timur',
    'Toraja Utara',
    'Makassar',
    'Parepare',
    'Palopo',
  ],

  'Sulawesi Tengah': [
    'Banggai Kepulauan',
    'Banggai',
    'Morowali',
    'Poso',
    'Donggala',
    'Toli-toli',
    'Buol',
    'Parigi Moutong',
    'Tojo Una-una',
    'Sigi',
    'Banggai Laut',
    'Morowali Utara',
    'Palu',
  ],

  'Sulawesi Tenggara': [
    'Buton',
    'Muna',
    'Konawe',
    'Kolaka',
    'Konawe Selatan',
    'Bombana',
    'Wakatobi',
    'Kolaka Utara',
    'Buton Utara',
    'Konawe Utara',
    'Kolaka Timur',
    'Konawe Kepulauan',
    'Muna Barat',
    'Buton Tengah',
    'Buton Selatan',
    'Kendari',
    'Baubau',
  ],

  'Sulawesi Utara': [
    'Bolaang Mongondow',
    'Minahasa',
    'Kepulauan Sangihe',
    'Kepulauan Talaud',
    'Minahasa Selatan',
    'Minahasa Utara',
    'Bolaang Mongondow Utara',
    'Siau Tagulandang Biaro',
    'Minahasa Tenggara',
    'Bolaang Mongondow Selatan',
    'Bolaang Mongondow Timur',
    'Manado',
    'Bitung',
    'Tomohon',
    'obagu',
  ],

  'Sumatera Barat': [
    'Kepulauan Mentawai',
    'Pesisir Selatan',
    'Solok',
    'Sijunjung',
    'Tanah Datar',
    'Padang Pariaman',
    'Agam',
    'Lima Puluh',
    'Pasaman',
    'Solok Selatan',
    'Dharmasraya',
    'Pasaman Barat',
    'Padang',
    'Solok',
    'Sawah Lunto',
    'Padang Panjang',
    'Bukittinggi',
    'Payakumbuh',
    'Pariaman',
  ],

  'Sumatera Selatan': [
    'Ogan Komering Ulu',
    'Ogan Komering Ilir',
    'Muara Enim',
    'Lahat',
    'Musi Rawas',
    'Musi Banyuasin',
    'Banyu Asin',
    'Ogan Komering Ulu Selatan',
    'Ogan Komering Ulu Timur',
    'Ogan Ilir',
    'Empat Lawang',
    'Penukal Abab Lematang Ilir',
    'Musi Rawas Utara',
    'Palembang',
    'Prabumulih',
    'Pagar Alam',
    'Lubuklinggau',
  ],

  'Sumatera Utara': [
    'Nias',
    'Mandailing Natal',
    'Tapanuli Selatan',
    'Tapanuli Tengah',
    'Tapanuli Utara',
    'Toba Samosir',
    'Labuhan Batu',
    'Asahan',
    'Simalungun',
    'Dairi',
    'Karo',
    'Deli Serdang',
    'Langkat',
    'Nias Selatan',
    'Humbang Hasundutan',
    'Pakpak Bharat',
    'Samosir',
    'Serdang Bedagai',
    'Batu Bara',
    'Padang Lawas Utara',
    'Padang Lawas',
    'Labuhan Batu Selatan',
    'Labuhan Batu Utara',
    'Nias Utara',
    'Nias Barat',
    'Sibolga',
    'Tanjung Balai',
    'Pematang Siantar',
    'Tebing Tinggi',
    'Medan',
    'Binjai',
    'Padangsidimpuan',
    'Gunungsitoli',
  ],

  'Yogyakarta': [
    'Kulon Progo',
    'Bantul',
    'Gunung Kidul',
    'Sleman',
    'Yogyakarta',
  ],
}