const alamats=[
  'Nanggroe Aceh Darussalam'->
  Sumatera Utara (Ibu Kota Medan)
  Sumatera Selatan (Ibu Kota Palembang)
  Sumatera Barat (Ibu Kota Padang)
  Bengkulu (Ibu Kota Bengkulu)
  Riau (Ibu Kota Pekanbaru)
  Kepulauan Riau (Ibu Kota Tanjung Pinang)
  Jambi (Ibu Kota Jambi)
  Lampung (Ibu Kota Bandar Lampung)
  Bangka Belitung (Ibu Kota Pangkal Pinang)
  Kalimantan Barat (Ibu Kota Pontianak)
  Kalimantan Timur (Ibu Kota Samarinda)
  Kalimantan Selatan (Ibu Kota Banjarbaru)
  Kalimantan Tengah (Ibu Kota Palangkaraya)
  Kalimantan Utara (Ibu Kota Tanjung Selor)
  Banten (Ibu Kota Serang)
  DKI Jakarta (Ibu Kota Jakarta)
  Jawa Barat (Ibu Kota Bandung)
  Jawa Tengah (Ibu Kota Semarang)
  Daerah Istimewa Yogyakarta (Ibu Kota Yogyakarta)
  Jawa Timur (Ibu Kota Surabaya)
  Bali (Ibu Kota Denpasar)
  Nusa Tenggara Timur (Ibu Kota Kupang)
  Nusa Tenggara Barat (Ibu Kota Mataram)
  Gorontalo (Ibu Kota Gorontalo)
  Sulawesi Barat (Ibu Kota Mamuju)
  Sulawesi Tengah (Ibu Kota Palu)
  Sulawesi Utara (Ibu Kota Manado)
  Sulawesi Tenggara (Ibu Kota Kendari)
  Sulawesi Selatan (Ibu Kota Makassar)
  Maluku Utara (Ibu Kota Sofifi)
  Maluku (Ibu Kota Ambon)
  Papua Barat (Ibu Kota Manokwari)
  Papua (Ibu Kota Jayapura)
  Papua Tengah (Ibu Kota Nabire)
  Papua Pegunungan (Ibu Kota Jayawijaya)
  Papua Selatan (Ibu Kota Merauke)
  Papua Barat Daya (Ibu Kota Sorong)'
]